language: node_js
node_js:
  - "8.9"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search